# Generated by Django 5.1.11 on 2025-09-01 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='section',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='time_limit_seconds',
        ),
        migrations.AddField(
            model_name='section',
            name='quiz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section', to='courses.quiz'),
        ),
    ]
