# Generated by Django 5.1.11 on 2025-09-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_quiz_section_remove_quiz_time_limit_seconds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='file',
        ),
        migrations.AddField(
            model_name='section',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
