# Generated by Django 5.1.11 on 2025-09-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_section_file_section_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
